#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          xtreamcodes
# Required-Start:    $mysql $network
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the xtreamcodes server daemon
# Description:       Controls the main xtreamcodes server daemon

/home/xtreamcodes/iptv_xtream_codes/start_services.sh
